//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladista
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikl
    {
        public Artikl()
        {
            this.stavke_eksternogDokumenta = new HashSet<stavke_eksternogDokumenta>();
            this.stavke_internogDokumenta = new HashSet<stavke_internogDokumenta>();
        }
    
        public int sifra { get; set; }
        public Nullable<decimal> nabavna_cijena { get; set; }
        public string naziv { get; set; }
        public Nullable<int> kolicina { get; set; }
        public Nullable<int> minimalna_kolicina { get; set; }
        public Nullable<int> pododjel { get; set; }
    
        public virtual Pododjel Pododjel1 { get; set; }
        public virtual ICollection<stavke_eksternogDokumenta> stavke_eksternogDokumenta { get; set; }
        public virtual ICollection<stavke_internogDokumenta> stavke_internogDokumenta { get; set; }
    }
}
