//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladista
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pododjel
    {
        public Pododjel()
        {
            this.Artikl = new HashSet<Artikl>();
        }
    
        public int sifra { get; set; }
        public string naziv { get; set; }
        public Nullable<int> kapacitet { get; set; }
        public Nullable<int> skladiste { get; set; }
    
        public virtual ICollection<Artikl> Artikl { get; set; }
        public virtual Skladiste Skladiste1 { get; set; }
    }
}
