//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladista
{
    using System;
    using System.Collections.Generic;
    
    public partial class stavke_eksternogDokumenta
    {
        public int id_dokumenta { get; set; }
        public int id_artikla { get; set; }
        public Nullable<int> kolicina { get; set; }
    
        public virtual Artikl Artikl { get; set; }
        public virtual eksterniDokument eksterniDokument { get; set; }
    }
}
