//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladista
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposlenik
    {
        public Zaposlenik()
        {
            this.eksterniDokument = new HashSet<eksterniDokument>();
            this.interniDokument = new HashSet<interniDokument>();
        }
    
        public int sifra { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public Nullable<int> uloga { get; set; }
    
        public virtual ICollection<eksterniDokument> eksterniDokument { get; set; }
        public virtual ICollection<interniDokument> interniDokument { get; set; }
        public virtual Uloga Uloga1 { get; set; }
    }
}
