//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skladista
{
    using System;
    using System.Collections.Generic;
    
    public partial class interniDokument
    {
        public interniDokument()
        {
            this.stavke_internogDokumenta = new HashSet<stavke_internogDokumenta>();
        }
    
        public int id_dokumenta { get; set; }
        public string sifra { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<int> vrsta { get; set; }
        public Nullable<int> izradio { get; set; }
    
        public virtual Zaposlenik Zaposlenik { get; set; }
        public virtual vrsta_internog_dokumenta vrsta_internog_dokumenta { get; set; }
        public virtual ICollection<stavke_internogDokumenta> stavke_internogDokumenta { get; set; }
    }
}
